# Generated by Django 2.1.dev20180205164247 on 2018-06-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('adjunto', models.FileField(upload_to='')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contrato', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Facturas', to='frontend.Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('publicada', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='licitacion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='FacturasA', to='frontend.Licitacion'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='licitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos', to='frontend.Licitacion'),
        ),
    ]
