# Generated by Django 2.1.dev20180205164247 on 2018-06-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Facturas', to='frontend.Contrato'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='licitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='FacturasA', to='frontend.Licitacion'),
        ),
    ]
